name: Jogo da Cobrinha

# Controlador do tempo que será feito a atualização dos arquivos.
on:
  schedule:
    # Será atualizado a cada 5 horas.
    - cron: "0 */5 * * *"
  # Permite executar na lista de Ações (utilizado para testes de build).
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Baixar repositório
      uses: actions/checkout@v2
    
    - name: Enviar mudanças
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
        force: true

    - name: Implantar no GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        # a branch de saída que mencionamos acima
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
